import '../globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'

import { Locale, i18n } from '../../../i18n-config'
import { Providers } from '@/components/providers'
import { config } from '@fortawesome/fontawesome-svg-core'
import { getDictionary } from '@/lib/dictionary'
import { sourceCodePro } from '@/lib/fonts'
import Footer from '@/components/footer/Footer'
import Header from '@/components/header/Header'
import type { Metadata } from 'next'

config.autoAddCss = false

export const metadata: Metadata = {
  title: 'Eder Ferreira',
  description: 'Generated by create next app',
}

export async function generateStaticParams(): Promise<{ lang: Locale }[]> {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  const dictionary = await getDictionary(params.lang)

  return (
    <html lang={params.lang} className="scroll-smooth">
      <body className={`${sourceCodePro.className} antialiased px-8 lg:px-32`}>
        <Providers dictionary={dictionary}>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
