import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'

import { Providers } from '@/components/providers'
import { config } from '@fortawesome/fontawesome-svg-core'
import { sourceCodePro } from '@/lib/fonts'
import Footer from '@/components/footer/Footer'
import Header from '@/components/header/Header'
import type { Metadata } from 'next'

config.autoAddCss = false

export const metadata: Metadata = {
  title: 'Eder Ferreira',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sourceCodePro.className} antialiased px-8 lg:px-32`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
